name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies    
      run: sudo apt-get install libgmp3-dev
    - name: configure
      run: sh ./configure && sudo rm /usr/bin/g++ && sudo mv /usr/bin/g++-9 /usr/bin/g++
    - name: make
      run: cd build && make
